import { contextBridge, ipcRenderer } from 'electron';

// Expose a safe API to the renderer process
contextBridge.exposeInMainWorld('vaultAPI', {
  status: () => ipcRenderer.invoke('vault:status'),
  getProjectsMomentum: () => ipcRenderer.invoke('vault:getProjectsMomentum'),
  getOpenLoops: (project?: string) => ipcRenderer.invoke('vault:getOpenLoops', project),
  createProject: (name: string, description?: string) => ipcRenderer.invoke('vault:createProject', name, description),
  saveMemory: (input: any) => ipcRenderer.invoke('vault:saveMemory', input),
  findMemory: (query: any) => ipcRenderer.invoke('vault:findMemory', query),
  recallContext: (query: any) => ipcRenderer.invoke('vault:recallContext', query),
  buildRecallMemoryContext: (input: unknown) => ipcRenderer.invoke('vault:buildRecallMemoryContext', input),
  listProjectWorkspaces: () => ipcRenderer.invoke('vault:listProjectWorkspaces'),
  getProjectWorkspace: (project: unknown) => ipcRenderer.invoke('vault:getProjectWorkspace', project),
  setProjectWorkspace: (input: unknown) => ipcRenderer.invoke('vault:setProjectWorkspace', input),
  removeProjectWorkspace: (project: unknown) => ipcRenderer.invoke('vault:removeProjectWorkspace', project),
  validateWorkspacePath: (workspacePath: unknown) => ipcRenderer.invoke('vault:validateWorkspacePath', workspacePath),
  buildProjectContextPack: (input: unknown) => ipcRenderer.invoke('vault:buildProjectContextPack', input),
  getLatest: (project?: string, limit?: number) => ipcRenderer.invoke('vault:getLatest', project, limit),
  getMemoryDetail: (uid: string) => ipcRenderer.invoke('vault:getMemoryDetail', uid),
  suggestSavePath: (project: string, memoryType: string, title: string) => ipcRenderer.invoke('vault:suggestSavePath', project, memoryType, title),
  detectSimilarMemories: (input: unknown) => ipcRenderer.invoke('vault:detectSimilarMemories', input),
  updateMemory: (uid: string, updates: any) => ipcRenderer.invoke('vault:updateMemory', uid, updates),
  promoteMemory: (uid: string) => ipcRenderer.invoke('vault:promoteMemory', uid),
  archiveMemory: (uid: string) => ipcRenderer.invoke('vault:archiveMemory', uid),
  resolveLoop: (input: unknown) => ipcRenderer.invoke('vault:resolveLoop', input),
  listProjectProposals: (query?: unknown) => ipcRenderer.invoke('vault:listProjectProposals', query),
  executeProjectReview: (projectName: string, options?: unknown) => ipcRenderer.invoke('vault:executeProjectReview', projectName, options),
  decideProjectProposal: (input: unknown) => ipcRenderer.invoke('vault:decideProjectProposal', input),
  mergeProject: (sourceName: string, targetName: string, options?: unknown) => ipcRenderer.invoke('vault:mergeProject', sourceName, targetName, options),
  addProjectRelationship: (input: unknown) => ipcRenderer.invoke('vault:addProjectRelationship', input),
  confirmMemoryDelete: (uid: string) => ipcRenderer.invoke('vault:confirmMemoryDelete', uid),
  createTask: (input: unknown) => ipcRenderer.invoke('vault:createTask', input),
  findTasks: (query: unknown) => ipcRenderer.invoke('vault:findTasks', query),
  getTask: (taskUid: string) => ipcRenderer.invoke('vault:getTask', taskUid),
  cancelTask: (taskUid: string) => ipcRenderer.invoke('vault:cancelTask', taskUid),
  getTaskQueueStats: () => ipcRenderer.invoke('vault:getTaskQueueStats'),
  getTaskExecutorStatus: () => ipcRenderer.invoke('vault:getTaskExecutorStatus'),
  startTaskExecutor: () => ipcRenderer.invoke('vault:startTaskExecutor'),
  stopTaskExecutor: () => ipcRenderer.invoke('vault:stopTaskExecutor'),
  getRecentLogs: (limit?: number, filters?: any) => ipcRenderer.invoke('vault:getRecentLogs', limit, filters),
  getAllSettings: () => ipcRenderer.invoke('vault:getAllSettings'),
  setSetting: (key: string, value: unknown) => ipcRenderer.invoke('vault:setSetting', key, value),
  getSecretSetting: (key: string) => ipcRenderer.invoke('vault:getSecretSetting', key),
  setSecretSetting: (key: string, value: string) => ipcRenderer.invoke('vault:setSecretSetting', key, value),
  getModelRoutingTable: () => ipcRenderer.invoke('vault:getModelRoutingTable'),
  setModelRoutingTable: (overrides: unknown) => ipcRenderer.invoke('vault:setModelRoutingTable', overrides),
  getOpenRouterModels: (apiKey: string) => ipcRenderer.invoke('vault:getOpenRouterModels', apiKey),
  testOpenRouterApiKey: (apiKey: string) => ipcRenderer.invoke('vault:testOpenRouterApiKey', apiKey),
  executeVaultApiAgent: (input: unknown) => ipcRenderer.invoke('vault:executeVaultApiAgent', input),
  getGraphifyRuntimeConfig: () => ipcRenderer.invoke('vault:getGraphifyRuntimeConfig'),
  saveGraphifyRuntimeConfig: (input: unknown) => ipcRenderer.invoke('vault:saveGraphifyRuntimeConfig', input),
  detectGraphifyRuntime: () => ipcRenderer.invoke('vault:detectGraphifyRuntime'),
  planGraphifyInstall: (input: unknown) => ipcRenderer.invoke('vault:planGraphifyInstall', input),
  getGraphifyProjectStatus: (project: string) => ipcRenderer.invoke('vault:getGraphifyProjectStatus', project),
  setGraphifyProjectSourceRoot: (project: string, sourceRoot: string) => ipcRenderer.invoke('vault:setGraphifyProjectSourceRoot', project, sourceRoot),
  chooseGraphifyProjectSourceRoot: (project: string) => ipcRenderer.invoke('vault:chooseGraphifyProjectSourceRoot', project),
  setGraphifyProjectEnabled: (project: string, enabled: boolean) => ipcRenderer.invoke('vault:setGraphifyProjectEnabled', project, enabled),
  getGraphifyBuildHistory: (project: string, limit?: number) => ipcRenderer.invoke('vault:getGraphifyBuildHistory', project, limit),
  getGraphifyArtifacts: (project: string) => ipcRenderer.invoke('vault:getGraphifyArtifacts', project),
  getGraphifyHtmlArtifact: (project: string) => ipcRenderer.invoke('vault:getGraphifyHtmlArtifact', project),
  readGraphifyArtifactReport: (project: string, options?: unknown) => ipcRenderer.invoke('vault:readGraphifyArtifactReport', project, options),
  getGraphifyArtifactUrl: (input: unknown) => ipcRenderer.invoke('vault:getGraphifyArtifactUrl', input),
  buildGraphifyProjectGraph: (input: unknown) => ipcRenderer.invoke('vault:buildGraphifyProjectGraph', input),
  openGraphifyArtifactFolder: (project: string) => ipcRenderer.invoke('vault:openGraphifyArtifactFolder', project),
  exportGraphifyArtifacts: (project: string) => ipcRenderer.invoke('vault:exportGraphifyArtifacts', project),
  getVaultCollabRuntimeConfig: () => ipcRenderer.invoke('vault:getVaultCollabRuntimeConfig'),
  saveVaultCollabRuntimeConfig: (input: unknown) => ipcRenderer.invoke('vault:saveVaultCollabRuntimeConfig', input),
  resetVaultCollabRuntimeConfig: () => ipcRenderer.invoke('vault:resetVaultCollabRuntimeConfig'),
  detectVaultCollabRuntime: () => ipcRenderer.invoke('vault:detectVaultCollabRuntime'),
  planVaultCollabInstall: () => ipcRenderer.invoke('vault:planVaultCollabInstall'),
  getVaultCollabDashboardSnapshot: (options?: unknown) => ipcRenderer.invoke('vault:getVaultCollabDashboardSnapshot', options),
  getVaultCollabHandoffActions: (handoffUid: string) => ipcRenderer.invoke('vault:getVaultCollabHandoffActions', handoffUid),
  performVaultCollabDashboardAction: (input: unknown) => ipcRenderer.invoke('vault:performVaultCollabDashboardAction', input),
  requestVaultCollabAgent: (input: unknown) => ipcRenderer.invoke('vault:requestVaultCollabAgent', input),
  listVaultCollabEventTypes: () => ipcRenderer.invoke('vault:listVaultCollabEventTypes'),
  activateVaultCollabPolicyPack: (input: unknown) => ipcRenderer.invoke('vault:activateVaultCollabPolicyPack', input),
  deactivateVaultCollabPolicyPack: (input: unknown) => ipcRenderer.invoke('vault:deactivateVaultCollabPolicyPack', input),
  approveVaultCollabLaunchRequest: (launchRequestUid: string) => ipcRenderer.invoke('vault:approveVaultCollabLaunchRequest', launchRequestUid),
  startVaultCollabLaunchRequest: (launchRequestUid: string) => ipcRenderer.invoke('vault:startVaultCollabLaunchRequest', launchRequestUid),
  getVaultCollabManagedTerminals: () => ipcRenderer.invoke('vault:getVaultCollabManagedTerminals'),
  controlVaultCollabManagedTerminal: (input: unknown) => ipcRenderer.invoke('vault:controlVaultCollabManagedTerminal', input),
  detectVaultCollabSourcePath: () => ipcRenderer.invoke('vault:detectVaultCollabSourcePath'),
  useDetectedVaultCollabSourcePath: () => ipcRenderer.invoke('vault:useDetectedVaultCollabSourcePath'),
  chooseVaultCollabSourcePath: () => ipcRenderer.invoke('vault:chooseVaultCollabSourcePath'),
  readSkillFile: (relativePath: string) => ipcRenderer.invoke('vault:readSkillFile', relativePath),
  getVaultStructure: () => ipcRenderer.invoke('vault:getVaultStructure'),
  readVaultFilePreview: (relativePath: string) => ipcRenderer.invoke('vault:readVaultFilePreview', relativePath),
  checkConnectionStatus: () => ipcRenderer.invoke('vault:checkConnectionStatus'),
  connectClaudeDesktop: () => ipcRenderer.invoke('vault:connectClaudeDesktop'),
  connectClaudeCode: () => ipcRenderer.invoke('vault:connectClaudeCode'),
  connectCodex: () => ipcRenderer.invoke('vault:connectCodex'),
  connectVaultCollabClients: () => ipcRenderer.invoke('vault:connectVaultCollabClients'),
  installSkillFile: (target: string) => ipcRenderer.invoke('vault:installSkillFile', target),
  refreshEnrichment: () => ipcRenderer.invoke('vault:refreshEnrichment'),
  disconnectClaudeDesktop: () => ipcRenderer.invoke('vault:disconnectClaudeDesktop'),
  disconnectClaudeCode: () => ipcRenderer.invoke('vault:disconnectClaudeCode'),
  disconnectCodex: () => ipcRenderer.invoke('vault:disconnectCodex'),
  disconnectVaultCollabClients: () => ipcRenderer.invoke('vault:disconnectVaultCollabClients'),
  uninstallSkillFile: (target: string) => ipcRenderer.invoke('vault:uninstallSkillFile', target),
  onTaskEvent: (callback: (event: unknown) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: unknown) => callback(payload);
    ipcRenderer.on('vault:taskEvent', listener);
    return () => {
      ipcRenderer.removeListener('vault:taskEvent', listener);
    };
  },
});
