import { contextBridge, ipcRenderer } from 'electron';

// Expose a safe API to the renderer process
contextBridge.exposeInMainWorld('vaultAPI', {
  status: () => ipcRenderer.invoke('vault:status'),
  getProjectsMomentum: () => ipcRenderer.invoke('vault:getProjectsMomentum'),
  getOpenLoops: (project?: string) => ipcRenderer.invoke('vault:getOpenLoops', project),
  createProject: (name: string, description?: string) => ipcRenderer.invoke('vault:createProject', name, description),
  saveMemory: (input: any) => ipcRenderer.invoke('vault:saveMemory', input),
  findMemory: (query: any) => ipcRenderer.invoke('vault:findMemory', query),
  recallContext: (query: any) => ipcRenderer.invoke('vault:recallContext', query),
  buildRecallMemoryContext: (input: unknown) => ipcRenderer.invoke('vault:buildRecallMemoryContext', input),
  getLatest: (project?: string, limit?: number) => ipcRenderer.invoke('vault:getLatest', project, limit),
  getMemoryDetail: (uid: string) => ipcRenderer.invoke('vault:getMemoryDetail', uid),
  suggestSavePath: (project: string, memoryType: string, title: string) => ipcRenderer.invoke('vault:suggestSavePath', project, memoryType, title),
  detectSimilarMemories: (input: unknown) => ipcRenderer.invoke('vault:detectSimilarMemories', input),
  updateMemory: (uid: string, updates: any) => ipcRenderer.invoke('vault:updateMemory', uid, updates),
  promoteMemory: (uid: string) => ipcRenderer.invoke('vault:promoteMemory', uid),
  archiveMemory: (uid: string) => ipcRenderer.invoke('vault:archiveMemory', uid),
  resolveLoop: (input: unknown) => ipcRenderer.invoke('vault:resolveLoop', input),
  listProjectProposals: (query?: unknown) => ipcRenderer.invoke('vault:listProjectProposals', query),
  executeProjectReview: (projectName: string, options?: unknown) => ipcRenderer.invoke('vault:executeProjectReview', projectName, options),
  decideProjectProposal: (input: unknown) => ipcRenderer.invoke('vault:decideProjectProposal', input),
  mergeProject: (sourceName: string, targetName: string, options?: unknown) => ipcRenderer.invoke('vault:mergeProject', sourceName, targetName, options),
  addProjectRelationship: (input: unknown) => ipcRenderer.invoke('vault:addProjectRelationship', input),
  confirmMemoryDelete: (uid: string) => ipcRenderer.invoke('vault:confirmMemoryDelete', uid),
  createTask: (input: unknown) => ipcRenderer.invoke('vault:createTask', input),
  findTasks: (query: unknown) => ipcRenderer.invoke('vault:findTasks', query),
  getTask: (taskUid: string) => ipcRenderer.invoke('vault:getTask', taskUid),
  cancelTask: (taskUid: string) => ipcRenderer.invoke('vault:cancelTask', taskUid),
  getTaskQueueStats: () => ipcRenderer.invoke('vault:getTaskQueueStats'),
  getTaskExecutorStatus: () => ipcRenderer.invoke('vault:getTaskExecutorStatus'),
  startTaskExecutor: () => ipcRenderer.invoke('vault:startTaskExecutor'),
  stopTaskExecutor: () => ipcRenderer.invoke('vault:stopTaskExecutor'),
  getRecentLogs: (limit?: number, filters?: any) => ipcRenderer.invoke('vault:getRecentLogs', limit, filters),
  getAllSettings: () => ipcRenderer.invoke('vault:getAllSettings'),
  setSetting: (key: string, value: unknown) => ipcRenderer.invoke('vault:setSetting', key, value),
  getSecretSetting: (key: string) => ipcRenderer.invoke('vault:getSecretSetting', key),
  setSecretSetting: (key: string, value: string) => ipcRenderer.invoke('vault:setSecretSetting', key, value),
  getModelRoutingTable: () => ipcRenderer.invoke('vault:getModelRoutingTable'),
  setModelRoutingTable: (overrides: unknown) => ipcRenderer.invoke('vault:setModelRoutingTable', overrides),
  getOpenRouterModels: (apiKey: string) => ipcRenderer.invoke('vault:getOpenRouterModels', apiKey),
  testOpenRouterApiKey: (apiKey: string) => ipcRenderer.invoke('vault:testOpenRouterApiKey', apiKey),
  executeVaultApiAgent: (input: unknown) => ipcRenderer.invoke('vault:executeVaultApiAgent', input),
  readSkillFile: (relativePath: string) => ipcRenderer.invoke('vault:readSkillFile', relativePath),
  getVaultStructure: () => ipcRenderer.invoke('vault:getVaultStructure'),
  readVaultFilePreview: (relativePath: string) => ipcRenderer.invoke('vault:readVaultFilePreview', relativePath),
  getSupportedLocalAdapters: () => ipcRenderer.invoke('vault:getSupportedLocalAdapters'),
  getLocalAdapterModels: (config: unknown) => ipcRenderer.invoke('vault:getLocalAdapterModels', config),
  detectLocalAdapterModel: (config: unknown) => ipcRenderer.invoke('vault:detectLocalAdapterModel', config),
  testLocalAdapterEnvironment: (config: unknown) => ipcRenderer.invoke('vault:testLocalAdapterEnvironment', config),
  executeEnabledLocalAdapter: (input: unknown) => ipcRenderer.invoke('vault:executeEnabledLocalAdapter', input),
  clearLocalAdapterSession: (adapterType: unknown) => ipcRenderer.invoke('vault:clearLocalAdapterSession', adapterType),
  clearLocalAdapterTaskSession: (adapterType: unknown, taskKey: unknown) => ipcRenderer.invoke('vault:clearLocalAdapterTaskSession', adapterType, taskKey),
  checkConnectionStatus: () => ipcRenderer.invoke('vault:checkConnectionStatus'),
  connectClaudeDesktop: () => ipcRenderer.invoke('vault:connectClaudeDesktop'),
  connectClaudeCode: () => ipcRenderer.invoke('vault:connectClaudeCode'),
  connectCodex: () => ipcRenderer.invoke('vault:connectCodex'),
  installSkillFile: (target: string) => ipcRenderer.invoke('vault:installSkillFile', target),
  refreshEnrichment: () => ipcRenderer.invoke('vault:refreshEnrichment'),
  disconnectClaudeDesktop: () => ipcRenderer.invoke('vault:disconnectClaudeDesktop'),
  disconnectClaudeCode: () => ipcRenderer.invoke('vault:disconnectClaudeCode'),
  disconnectCodex: () => ipcRenderer.invoke('vault:disconnectCodex'),
  uninstallSkillFile: (target: string) => ipcRenderer.invoke('vault:uninstallSkillFile', target),
  onTaskEvent: (callback: (event: unknown) => void) => {
    const listener = (_event: Electron.IpcRendererEvent, payload: unknown) => callback(payload);
    ipcRenderer.on('vault:taskEvent', listener);
    return () => {
      ipcRenderer.removeListener('vault:taskEvent', listener);
    };
  },
});
